const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {origin,routes,forState}=require('../dist/routes.js');
const root=path.resolve(__dirname,'..');
const read=file=>fs.readFileSync(path.join(root,file),'utf8');
const escape=value=>String(value).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
// Execute the existing view renderers against a tiny DOM adapter. Content stays
// sourced from the same lessons and reference data as the interactive application.
const nodes=new Map();
function node(selector){if(!nodes.has(selector))nodes.set(selector,{innerHTML:'',textContent:'',dataset:{},style:{},classList:{toggle(){}},addEventListener(){},setAttribute(){},querySelector:node});return nodes.get(selector)}
const document={querySelector:node,querySelectorAll:()=>[],addEventListener(){}};
const context=vm.createContext({document,localStorage:{getItem:()=>null},GitOrbitRoutes:{origin,routes,forState},console});
vm.runInContext(read('dist/beginner.js'),context);
vm.runInContext(read('dist/beyond.js'),context);
const app=read('dist/app.js');
vm.runInContext(app.slice(0,app.indexOf("window.addEventListener('resize'")),context);
function between(start,end){return app.slice(app.indexOf(start),app.indexOf(end,app.indexOf(start)))}
vm.runInContext(between('function renderLessonPreview()','function render(){'),context);
vm.runInContext(between('const commands=','document.addEventListener(\'click\''),context);
function links(html){return html.replace(/<button([^>]*data-(?:lesson|view)="[^"]+"[^>]*)>([\s\S]*?)<\/button>/g,(_,attributes,content)=>{
 const lesson=attributes.match(/data-lesson="(\d+)"/),view=attributes.match(/data-view="([^"]+)"/);
 const route=lesson?forState('lesson-intro',Number(lesson[1])):forState(view[1],0);
 return `<a${attributes} href="${route.path}">${content}</a>`;
})}
const template=read('src/index.html');
for(const route of routes){
 nodes.clear();
 vm.runInContext(`lesson=${route.lesson??0};mode=pathFor(lesson);view=${JSON.stringify(route.view)};renderNav();`,context);
 const views={introduction:['introduction-view','renderIntroduction()'], 'lesson-intro':['lesson-intro-view','renderLessonPreview()'],reference:['reference-view','renderReference()'],challenge:['challenge-view','renderChallenges()'],beyond:['beyond-view','renderBeyond()']};
 const [id,render]=views[route.view];vm.runInContext(render,context);
 let content=node('#'+id).innerHTML;
 if(route.view==='introduction'){
  // Include the initial recipe text generated by renderRecipe too.
  for(const selector of ['recipe-versions','recipe-preview','recipe-explanation']){
   const entry=node('#'+selector),value=entry.innerHTML||escape(entry.textContent);
   content=content.replace(new RegExp(`(<[^>]+id="${selector}"[^>]*>)[\\s\\S]*?(</(?:div|p)>)`),`$1${value}$2`);
  }
 }
 if(route.view==='reference')content=content.replace('<div class="reference-grid" id="reference-grid"></div>',`<div class="reference-grid" id="reference-grid">${node('#reference-grid').innerHTML}</div>`).replace('<p id="reference-count" class="reference-count" role="status"></p>',`<p id="reference-count" class="reference-count" role="status">${escape(node('#reference-count').textContent)}</p>`);
 let html=template.replace(/__TITLE__/g,escape(route.title)).replace(/__DESCRIPTION__/g,escape(route.description)).replace(/__URL__/g,origin+route.path);
 const schema={ '@context':'https://schema.org','@graph':[
  {'@type':'WebSite','@id':origin+'/#website',url:origin+'/',name:'Git Orbit',description:routes[0].description,inLanguage:'en'},
  {'@type':route.lesson===undefined?'WebPage':'LearningResource','@id':origin+route.path+'#page',url:origin+route.path,name:route.title,description:route.description,isPartOf:{'@id':origin+'/#website'},inLanguage:'en',isAccessibleForFree:true,...(route.lesson===undefined?{}:{learningResourceType:'Interactive lesson',educationalLevel:'Beginner'})}
 ]};
 html=html.replace('__SCHEMA__',JSON.stringify(schema).replaceAll('<','\\u003c'));
 html=html.replace(new RegExp(`(<section id="${id}"[^>]*)( hidden)(></section>)`),`$1>${links(content)}</section>`);
 html=html.replace('<div id="lab-view">','<div id="lab-view" hidden>');
 html=html.replace('<nav id="lesson-nav" class="lesson-nav" aria-label="Lessons"></nav>',`<nav id="lesson-nav" class="lesson-nav" aria-label="Lessons">${links(node('#lesson-nav').innerHTML)}</nav>`);
 html=links(html);
 html=html.replace(/<h1>[\s\S]*?<\/h1>/,`<h1>${route.view==='introduction'?'Learn <span>Git &amp; GitHub.</span>':escape(route.title.split(' | ')[0])}</h1>`);
 html=html.replace('<strong id="breadcrumb">Learning lab</strong>',`<strong id="breadcrumb">${escape(route.view==='lesson-intro'?'Lesson overview':route.title.split(' | ')[0])}</strong>`);
 // The static current-page state also works without JavaScript.
 html=html.replace(/<a([^>]*data-view="([^"]+)"[^>]*)>/g,(_,attrs,view)=>`<a${attrs.replace(/ class="active"/,'')}${view===route.view||view==='lab'&&route.view==='lesson-intro'?' class="active" aria-current="page"':''}>`);
 const file=path.join(root,'dist',route.path,'index.html');fs.mkdirSync(path.dirname(file),{recursive:true});fs.writeFileSync(file,html);
}
fs.writeFileSync(path.join(root,'dist/sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${routes.map(route=>`  <url><loc>${origin+route.path}</loc></url>`).join('\n')}\n</urlset>\n`);
console.log(`Generated ${routes.length} crawlable pages and sitemap.xml.`);
